spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taxi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

coordinate:
  start-longitude: 50.189683
  start-latitude: 53.222579
  finish-longitude: 50.102834
  finish-latitude: 53.199131

yandex:
  url: http://taxi-routeinfo.taxi.yandex.net/taxi_info
  clid: ${YANDEX_CLID}
  apiKey: ${YANDEX_APIKEY}

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true